### PR TITLE
Add support for template-haskell-2.12.0.0 in GHC-8.2

### PR DESCRIPTION
**Pull request by duog**
The DataD and NewtypeD constructors are changing.
See:https://ghc.haskell.org/trac/ghc/wiki/Migration/8.2

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks @duog! I'll merge this and release if no one else does, but I'm currently trying to foist maintainership onto someone else, as per #6, so let's see if @tomberek @mgajda wants to do it first (or if you want to become a maintainer!).

**Comment by duog** [comment]
Thanks; I'm not a user, I just needed this as a dependency.

**Comment by ndmitchell** [comment]
I'm neither a user nor someone with a dependency, hency why I'm trying to pass it on to someone who is more invested in it.

**Comment by mgajda** [comment]
I am afraid @tomberek is better address ATM. I am time strained Now.

**Comment by ndmitchell** [comment]
Thanks @duog - I merged, tested and made a release.

**Pull request merged**
