### PR TITLE
Hse 1.18

### PR DESCRIPTION
**Pull request by Lemmih**
This completes the conversion to hse-1.18.

### CODE REVIEW

**Comment by Lemmih** [comment]
Oh man, using TH across four versions of GHC is a nightmare.

**Comment by Lemmih** [comment]
Hm, the generated code in src/Data/Derive/*.hs is different on ghc-7.8 and ghc-8.0 compared to ghc-7.10. I have no idea why; it only happens with travis and I cannot replicate it. On my box, I get identical output with ghc-7.8, ghc-7.10, and ghc-8.0.

**Comment by ndmitchell** [comment]
Thanks for your impressive efforts, that's looks like a lot of work has gone into it.

I've never had an issue with different code generated on different versions - that is weird. It should be entirely dependent on the haskell-src-exts version, which makes it all the more weirder, as that is consistent between them.

**Comment by Lemmih** [comment]
You're welcome. When I apply for a job at Barclays, I'll mention derive as a project I've been involved with. :)

**Pull request merged**
