### PR TITLE
convert type ([] :: * -> *)

### PR DESCRIPTION
**Pull request by strake**

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks, merged. Let me know if it would be of benefit to make a release including this change.

**Comment by strake** [comment]
I think it would, as this caused me some grief in actual usage, but it ought to also convert (->); I'm on it

**Comment by ndmitchell** [comment]
OK, I'll merge that one and make a release, unless you have any other patches coming shortly.

**Comment by strake** [comment]
On 14/03/2015 at 14:13:18 -0700, Neil Mitchell wrote:
> OK, I'll merge that one and make a release, unless you have any other patches coming shortly.

That's all for now, thanks.

**Comment by ndmitchell** [comment]
Great, I'll make a release tomorrow.

**Comment by ndmitchell** [comment]
At the moment hashable won't build on GHC 7.10.1 so I'm holding off on a release until I can check derive on there - hopefully a day or so.

**Comment by ndmitchell** [comment]
Released as 2.5.22.

**Pull request merged**
